name: C2C - Patch Bump

on:
  workflow_dispatch:
    branches:
      - release/*


permissions:
  contents: write

jobs:
  bump-patch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Fetch all tags
      run: git fetch --tags origin

    - name: Get last version from tags
      id: read_version
      run: |
        version=$(git tag --sort=-v:refname | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$" | head -n 1)
        echo "version: $version"
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Bump patch version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        release_version: ${{ steps.read_version.outputs.version }}
      run: |
        git checkout main
        IFS='/' read -r _ version <<< "$release_version"
        IFS='.' read -r yy mm patch <<< "$version"
        patch=$((patch + 1))
        new_version="$yy.$mm.$patch"
        echo "new version: $new_version"

        release_tag="release/$new_version"
        echo "release_tag: $release_tag"
        git tag "$release_tag"
        git push origin "$release_tag"