name: C2C - Create Release Branch

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      confirm:
        description: 'Confirm creating of release branch'
        required: true
        default: 'yes'

permissions:
  contents: write

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        fetch-tags: true  # загрузить теги

    - name: Get last version from tags
      id: read_version
      run: |
        git checkout main
        full_version=$(git tag --sort=-v:refname | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$" | head -n 1)
        result=$(git tag --sort=-v:refname)
        echo "ccc $result"
        echo "Full version: $full_version"
        echo "full_version=$full_version" >> $GITHUB_OUTPUT
    - name: Create release branch and move tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        full_version: ${{ steps.read_version.outputs.full_version }}
      run: |
        git checkout main
        IFS='.' read -r yy mm patch <<< "$full_version"
        short_version=${yy}.${mm}
        git checkout -b release/$short_version
        git push origin release/$short_version
        release_tag="release/$full_version"
        echo "release_tag: $release_tag"
        git tag "$release_tag"
        git push origin "$release_tag"

    - name: Create new version tag in main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        full_version: ${{ steps.read_version.outputs.full_version }}
      run: |
        git fetch origin main
        git checkout main
        IFS='.' read -r yy mm patch <<< "$full_version"
        mm=$((mm + 1))
        if [ $mm -gt 12 ]; then
          mm=1
          yy=$((yy + 1))
        fi
        patch=0
        new_version="$yy.$mm.$patch"
        echo "new version: $new_version"
        git tag "$new_version"
        git push origin "$new_version"

        git tag -d "$full_version"
        git push origin --delete "$full_version"