name: C2C - Create Release Branch

on:
  workflow_dispatch:
    branches:
      - develop
    inputs:
      confirm:
        description: 'Confirm creating of release branch'
        required: true
        default: 'yes'

permissions:
  contents: write

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read version from file
      id: read_version
      run: |
        git fetch origin c2c-develop
        git checkout c2c-develop
        current_version=$(git describe --tags --abbrev=0 --match "v[0-9]*.[0-9]*.[0-9]*" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$')
        current_version=$(echo "$current_version" | cut -d '.' -f 1,2) # Use only yy.mm part of the version
        echo "Current version: $current_version"
        echo "Current version (without minor): $new_version"
        echo "current_version=$current_version" >> $GITHUB_OUTPUT
    # - name: Create tag and release branch
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     NEW_VERSION: ${{ steps.read_version.outputs.new_version }}
    #   run: |
    #     tag_name="$NEW_VERSION-c2c"
    #     git fetch origin c2c-develop
    #     git checkout c2c-develop
    #     git tag $tag_name
    #     git push origin $tag_name
    #     git checkout -b release/$tag_name
    #     git push origin release/$tag_name